--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: services_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.services_category OWNER TO postgres;

--
-- Name: services_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_courses (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.services_courses OWNER TO postgres;

--
-- Name: services_courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_normaluser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_normaluser (
    id bigint NOT NULL,
    username character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    password character varying(100) NOT NULL
);


ALTER TABLE public.services_normaluser OWNER TO postgres;

--
-- Name: services_normaluser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_normaluser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_normaluser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_normaluserprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_normaluserprofile (
    id bigint NOT NULL,
    bio text NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.services_normaluserprofile OWNER TO postgres;

--
-- Name: services_normaluserprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_normaluserprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_normaluserprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_project; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_project (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    image character varying(300) NOT NULL,
    subtitle character varying(200) NOT NULL,
    url character varying(200) NOT NULL
);


ALTER TABLE public.services_project OWNER TO postgres;

--
-- Name: services_project_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_service; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_service (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.services_service OWNER TO postgres;

--
-- Name: services_service_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_technology; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_technology (
    id bigint NOT NULL,
    name character varying(200) NOT NULL
);


ALTER TABLE public.services_technology OWNER TO postgres;

--
-- Name: services_technology_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_technology ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_technology_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add service	7	add_service
26	Can change service	7	change_service
27	Can delete service	7	delete_service
28	Can view service	7	view_service
29	Can add category	8	add_category
30	Can change category	8	change_category
31	Can delete category	8	delete_category
32	Can view category	8	view_category
33	Can add courses	9	add_courses
34	Can change courses	9	change_courses
35	Can delete courses	9	delete_courses
36	Can view courses	9	view_courses
37	Can add normal user	10	add_normaluser
38	Can change normal user	10	change_normaluser
39	Can delete normal user	10	delete_normaluser
40	Can view normal user	10	view_normaluser
41	Can add normal user profile	11	add_normaluserprofile
42	Can change normal user profile	11	change_normaluserprofile
43	Can delete normal user profile	11	delete_normaluserprofile
44	Can view normal user profile	11	view_normaluserprofile
45	Can add project	12	add_project
46	Can change project	12	change_project
47	Can delete project	12	delete_project
48	Can view project	12	view_project
49	Can add technology	13	add_technology
50	Can change technology	13	change_technology
51	Can delete technology	13	delete_technology
52	Can view technology	13	view_technology
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1500000$Cb4RAnDuD6pSTJvkiqUfzM$bUePnYjVyLxDIJ/6rwxgITTBLM8qt+kOx2SxnlR4qNo=	2026-09-18 09:55:01.567601+05:45	t	admin				t	t	2026-09-18 09:54:18.916721+05:45
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-09-18 09:56:26.546825+05:45	1	Mobile Development	1	[{"added": {}}]	7	1
2	2026-09-18 10:00:53.388444+05:45	2	AI/ML	1	[{"added": {}}]	7	1
3	2026-09-18 10:15:31.939844+05:45	1	English	1	[{"added": {}}]	8	1
4	2026-09-18 10:15:42.61587+05:45	2	Maths	1	[{"added": {}}]	8	1
5	2026-09-18 10:16:26.546128+05:45	1	Basic	1	[{"added": {}}]	9	1
6	2026-09-18 10:20:53.491404+05:45	1	prateek_74	1	[{"added": {}}]	10	1
7	2026-09-18 10:21:16.872649+05:45	2	pk	1	[{"added": {}}]	10	1
8	2026-09-18 10:21:34.149045+05:45	1	pk	1	[{"added": {}}]	11	1
9	2026-09-18 12:50:12.329441+05:45	1	Python	1	[{"added": {}}]	13	1
10	2026-09-18 12:50:21.292318+05:45	2	Django	1	[{"added": {}}]	13	1
11	2026-09-18 12:50:51.348385+05:45	3	Vue.js	1	[{"added": {}}]	13	1
12	2026-09-18 12:55:49.793691+05:45	4	yggh	1	[{"added": {}}]	13	1
13	2026-09-18 12:55:55.271217+05:45	1	WebGIS Application	1	[{"added": {}}]	12	1
14	2026-09-18 12:56:07.761017+05:45	4	yggh	3		13	1
15	2026-09-18 12:56:34.092897+05:45	2	WebGIS Application	1	[{"added": {}}]	12	1
16	2026-09-18 12:56:50.754781+05:45	1	WebGIS Application	3		12	1
17	2026-09-18 13:36:07.102639+05:45	2	AI/ML	3		7	1
18	2026-09-18 13:36:07.102639+05:45	1	Mobile Development	3		7	1
19	2026-09-18 13:36:41.181056+05:45	3	GeoPortal Solutions	1	[{"added": {}}]	7	1
20	2026-09-18 13:37:00.826991+05:45	4	Municipal Management Systems	1	[{"added": {}}]	7	1
21	2026-09-18 13:37:23.020948+05:45	5	AI & Machine Learning	1	[{"added": {}}]	7	1
22	2026-09-18 13:37:45.512353+05:45	6	Data Management	1	[{"added": {}}]	7	1
23	2026-09-18 13:38:10.3289+05:45	7	Web & App Development	1	[{"added": {}}]	7	1
24	2026-09-18 13:38:26.150897+05:45	8	Interactive Dashboards	1	[{"added": {}}]	7	1
25	2026-09-18 22:37:45.436031+05:45	2	Explore Nepal	2	[{"changed": {"fields": ["Name", "Subtitle", "Description", "Image", "Url", "Technologies"]}}]	12	1
26	2026-09-18 22:40:51.64704+05:45	2	Explore Nepal	2	[]	12	1
27	2026-09-18 22:56:36.266014+05:45	3	Custom Chatbot Service	1	[{"added": {}}]	12	1
28	2026-09-18 22:56:43.632887+05:45	2	Explore Nepal	2	[{"changed": {"fields": ["Url"]}}]	12	1
29	2026-09-18 22:56:46.937116+05:45	2	Explore Nepal	2	[]	12	1
30	2026-09-18 22:59:52.530665+05:45	4	Municipal Management System	1	[{"added": {}}]	12	1
31	2026-09-18 23:01:35.744935+05:45	5	Geospatial Data Center	1	[{"added": {}}]	12	1
32	2026-09-18 23:03:19.07456+05:45	2	Explore Nepal	2	[]	12	1
33	2026-09-18 23:03:50.873639+05:45	4	Municipal Management System	2	[]	12	1
34	2026-09-18 23:04:14.027313+05:45	2	Explore Nepal	2	[]	12	1
35	2026-09-18 23:04:50.241387+05:45	5	Geospatial Data Center	2	[]	12	1
36	2026-09-18 23:04:54.920218+05:45	4	Municipal Management System	2	[]	12	1
37	2026-09-18 23:04:57.846024+05:45	3	Custom Chatbot Service	2	[]	12	1
38	2026-09-18 23:05:00.32042+05:45	2	Explore Nepal	2	[]	12	1
39	2026-09-18 23:05:47.762678+05:45	5	Geospatial Data Center	2	[]	12	1
40	2026-09-18 23:05:50.69235+05:45	4	Municipal Management System	2	[]	12	1
41	2026-09-18 23:05:53.459595+05:45	3	Custom Chatbot Service	2	[]	12	1
42	2026-09-18 23:05:56.013244+05:45	2	Explore Nepal	2	[]	12	1
43	2026-09-18 23:06:05.240201+05:45	2	Explore Nepal	2	[]	12	1
44	2026-09-18 23:06:12.130989+05:45	2	Explore Nepal	2	[]	12	1
45	2026-09-18 23:06:22.786808+05:45	3	Custom Chatbot Service	2	[]	12	1
46	2026-09-18 23:06:47.215857+05:45	5	Geospatial Data Center	2	[{"changed": {"fields": ["Description"]}}]	12	1
47	2026-09-18 23:07:41.73946+05:45	4	Municipal Management System	2	[]	12	1
48	2026-09-18 23:20:30.67364+05:45	5	Geospatial Data Center	2	[]	12	1
49	2026-09-18 23:20:35.243689+05:45	4	Municipal Management System	2	[{"changed": {"fields": ["Image"]}}]	12	1
50	2026-09-18 23:20:39.092066+05:45	3	Custom Chatbot Service	2	[{"changed": {"fields": ["Image"]}}]	12	1
51	2026-09-18 23:20:48.230137+05:45	2	Explore Nepal	2	[{"changed": {"fields": ["Image"]}}]	12	1
52	2026-09-18 23:21:13.355716+05:45	2	Explore Nepal	2	[]	12	1
53	2026-09-18 23:21:16.215528+05:45	3	Custom Chatbot Service	2	[]	12	1
54	2026-09-18 23:21:25.959371+05:45	5	Geospatial Data Center	2	[{"changed": {"fields": ["Image"]}}]	12	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	services	service
8	services	category
9	services	courses
10	services	normaluser
11	services	normaluserprofile
12	services	project
13	services	technology
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-18 01:26:04.818964+05:45
2	auth	0001_initial	2026-09-18 01:26:04.913203+05:45
3	admin	0001_initial	2026-09-18 01:26:04.94446+05:45
4	admin	0002_logentry_remove_auto_add	2026-09-18 01:26:04.967812+05:45
5	admin	0003_logentry_add_action_flag_choices	2026-09-18 01:26:04.975378+05:45
6	contenttypes	0002_remove_content_type_name	2026-09-18 01:26:04.991483+05:45
7	auth	0002_alter_permission_name_max_length	2026-09-18 01:26:05.001996+05:45
8	auth	0003_alter_user_email_max_length	2026-09-18 01:26:05.01077+05:45
9	auth	0004_alter_user_username_opts	2026-09-18 01:26:05.017976+05:45
10	auth	0005_alter_user_last_login_null	2026-09-18 01:26:05.030593+05:45
11	auth	0006_require_contenttypes_0002	2026-09-18 01:26:05.036338+05:45
12	auth	0007_alter_validators_add_error_messages	2026-09-18 01:26:05.045926+05:45
13	auth	0008_alter_user_username_max_length	2026-09-18 01:26:05.061003+05:45
14	auth	0009_alter_user_last_name_max_length	2026-09-18 01:26:05.071203+05:45
15	auth	0010_alter_group_name_max_length	2026-09-18 01:26:05.082576+05:45
16	auth	0011_update_proxy_permissions	2026-09-18 01:26:05.092183+05:45
17	auth	0012_alter_user_first_name_max_length	2026-09-18 01:26:05.102466+05:45
18	sessions	0001_initial	2026-09-18 01:26:05.118657+05:45
19	services	0001_initial	2026-09-18 01:33:04.408617+05:45
20	services	0002_category	2026-09-18 10:12:37.621392+05:45
21	services	0003_courses	2026-09-18 10:12:37.638597+05:45
22	services	0004_normaluser_normaluserprofile	2026-09-18 10:19:32.236958+05:45
23	services	0005_technology_project	2026-09-18 10:27:10.426389+05:45
24	services	0006_project_description_project_image_project_subtitle_and_more	2026-09-18 22:27:04.35811+05:45
25	services	0007_remove_project_technologies	2026-09-18 22:47:28.630802+05:45
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
ifgfectnvuxj1rpkc0xpijou03kbxr0c	.eJxVjDsOwjAQBe_iGln-JjYlPWew1rsbHEC2FCcV4u4QKQW0b2beSyTY1pK2zkuaSZyFFqffLQM-uO6A7lBvTWKr6zJnuSvyoF1eG_Hzcrh_BwV6-dYuqDgoayxEJkaGaEM2bjBIQIFgcqB1VsG7KTKa0apozOg0Z4XeZyveH-KSN8M:1x7PvF:sQ-W3jQJ9M_kUl4NyZdAOd3-hTT9US4rT2BjCDzfkhY	2026-10-02 09:55:01.572629+05:45
\.


--
-- Data for Name: services_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services_category (id, name) FROM stdin;
1	English
2	Maths
\.


--
-- Data for Name: services_courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services_courses (id, title, description, category_id) FROM stdin;
1	Basic	aaa	1
\.


--
-- Data for Name: services_normaluser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services_normaluser (id, username, email, password) FROM stdin;
1	prateek_74	magarpratik74@gmail.com	123456
2	pk	magar@gmail.com	234234
\.


--
-- Data for Name: services_normaluserprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services_normaluserprofile (id, bio, user_id) FROM stdin;
1	okkk	2
\.


--
-- Data for Name: services_project; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services_project (id, name, description, image, subtitle, url) FROM stdin;
2	Explore Nepal	A dynamic platform showcasing Nepal's culture, destinations, and travel tools — combining design, data, and storytelling.		Travel & Culture Platform	
3	Custom Chatbot Service	Custom chatbot service with a custom knowledge base that clients can train to provide intelligent, context-aware responses tailored to their specific needs.		AI Assistant Platform	
5	Geospatial Data Center	A centralized platform that offers comprehensive spatial data, interactive mapping tools, and intelligent visualizations designed to support planners, researchers, educators, and government bodies in making informed and impactful choices.		Data Management and Geospatial Visualizations	
4	Municipal Management System	A geo-based system developed for municipalities to assign and manage house numbers efficiently and accurately.		Government Management Platform	
\.


--
-- Data for Name: services_service; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services_service (id, title, description) FROM stdin;
3	GeoPortal Solutions	Interactive geospatial platforms for managing and visualizing spatial information.
4	Municipal Management Systems	Digital systems that support municipalities and improve information management.
5	AI & Machine Learning	AI-driven solutions for automation, analysis, and intelligent decision-making.
6	Data Management	Efficient systems for storing, managing, analyzing, and visualizing data.
7	Web & App Development	Modern web and application solutions tailored to organizational needs.
8	Interactive Dashboards	Interactive dashboards that turn complex data into useful insights
\.


--
-- Data for Name: services_technology; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services_technology (id, name) FROM stdin;
1	Python
2	Django
3	Vue.js
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 54, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: services_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_category_id_seq', 2, true);


--
-- Name: services_courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_courses_id_seq', 1, true);


--
-- Name: services_normaluser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_normaluser_id_seq', 2, true);


--
-- Name: services_normaluserprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_normaluserprofile_id_seq', 1, true);


--
-- Name: services_project_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_project_id_seq', 5, true);


--
-- Name: services_service_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_service_id_seq', 8, true);


--
-- Name: services_technology_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_technology_id_seq', 4, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: services_category services_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_category
    ADD CONSTRAINT services_category_pkey PRIMARY KEY (id);


--
-- Name: services_courses services_courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_courses
    ADD CONSTRAINT services_courses_pkey PRIMARY KEY (id);


--
-- Name: services_normaluser services_normaluser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_normaluser
    ADD CONSTRAINT services_normaluser_pkey PRIMARY KEY (id);


--
-- Name: services_normaluserprofile services_normaluserprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_normaluserprofile
    ADD CONSTRAINT services_normaluserprofile_pkey PRIMARY KEY (id);


--
-- Name: services_normaluserprofile services_normaluserprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_normaluserprofile
    ADD CONSTRAINT services_normaluserprofile_user_id_key UNIQUE (user_id);


--
-- Name: services_project services_project_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_project
    ADD CONSTRAINT services_project_pkey PRIMARY KEY (id);


--
-- Name: services_service services_service_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_service
    ADD CONSTRAINT services_service_pkey PRIMARY KEY (id);


--
-- Name: services_technology services_technology_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_technology
    ADD CONSTRAINT services_technology_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: services_courses_category_id_77d8362f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_courses_category_id_77d8362f ON public.services_courses USING btree (category_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_courses services_courses_category_id_77d8362f_fk_services_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_courses
    ADD CONSTRAINT services_courses_category_id_77d8362f_fk_services_category_id FOREIGN KEY (category_id) REFERENCES public.services_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_normaluserprofile services_normaluserp_user_id_b2299145_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_normaluserprofile
    ADD CONSTRAINT services_normaluserp_user_id_b2299145_fk_services_ FOREIGN KEY (user_id) REFERENCES public.services_normaluser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

