# Generated by Django 6.1.1 on 2026-09-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
