# Generated by Django 6.1.1 on 2026-09-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_project_description_project_image_project_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
    ]
