# Generated by Django 6.1.1 on 2026-09-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='normaluserprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
        migrations.DeleteModel(
            name='NormalUserProfile',
        ),
    ]
