# Generated by Django 6.1.1 on 2026-09-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)')], max_length=50)),
                ('url', models.URLField()),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='team.teammember')),
            ],
        ),
    ]
