# Generated by Django 6.1.1 on 2026-09-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_address_jobapplication_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default='Not provided', max_length=200),
            preserve_default=False,
        ),
    ]
